config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "spends#index"
  resources :spends
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :spends

  validates :nickname, presence: true
  # PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  # validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  before_action :set_spreadsheet

  def index
  @data = []
  @total_outflow = Hash.new(0)
  @total_Inflow = Hash.new(0)
  (2..@sp.num_rows).each do |row|
    date = @sp["B#{row}"] 
    next unless date.to_s.split('/')[1] == '03'

    row_data = {}
    row_data['日付'] = date
    row_data['入出金'] = @sp["C#{row}"]
    row_data['項目'] = @sp["D#{row}"]
    row_data['メモ'] = @sp["E#{row}"]
    row_data['入出金方法'] = @sp["F#{row}"]
    row_data['金額'] = @sp["G#{row}"]
      
    amount = @sp["G#{row}"].to_i
    if @sp["C#{row}"] == '出金'
      @total_outflow[date] += amount
    else
      @total_Inflow[date] += amount
    end
      
    @data << row_data 
  end

  if params[:query].present?
    query = Regexp.new(params[:query], Regexp::IGNORECASE)
    @data = @data.select { |row| row.values.any? { |value| value.to_s.match?(query) } }
  end
  end

  private
  def set_spreadsheet
    session = GoogleDrive::Session.from_config("config.json")
    @sp = session.spreadsheet_by_url(ENV["SPREAD_URL"]).worksheet_by_title("フォームの回答 1")
  end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseholdAccountsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="container">
        <div class="title-head">
          <%= link_to "家計簿アプリ(仮)", root_path, class: :title__btn %>
        </div>
          <div class="user-head">
            <% if user_signed_in? %>
              <div class="user-menu">
                <div class="user_menu_btn" id= "login_user">  
                  <%= current_user.nickname%>▼
                </div>
                <div>  
                  <%= link_to "ユーザー詳細", user_path(current_user.id), class: "nav__btn btn hidden", id:"option_btn0" %>
                </div>
                <div> 
                  <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav__logout hidden", id:"option_btn1" %> 
                </div>
              </div>
                <% else %>
                <div class="user-menu">
                  <%= link_to "ログイン", new_user_session_path %>
                  /
                  <%= link_to "新規登録", new_user_registration_path %>
                </div>
            <% end %>
          </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="app-footer">household_accounts_app</p>
    </footer>
  </body>
</html>

app/views/spends/_form.html.erb
<div class="hidden">
  フォーム
</div>

app/views/spends/index.html.erb
<main class="main-body">
  <% if user_signed_in? %>
    <%= form_with(url: spends_path, method: :get, local: true) do %>
      <%= label_tag :query, "検索したい項目:" %>
      <%= text_field_tag :query, params[:query], autocomplete: "off" %>
      <%= submit_tag "検索", name: nil %>
    <% end %>

    <div class="main-table">
      <div class="left-side">
        <table>
          <tr>
            <th style="border: 1px solid black; padding: 10px;">日付</th>
            <th style="border: 1px solid black; padding: 10px;">入出金</th>
            <th style="border: 1px solid black; padding: 10px;">項目</th>
            <th style="border: 1px solid black; padding: 10px;">メモ</th>
            <th style="border: 1px solid black; padding: 10px;">入出金方法</th>
            <th style="border: 1px solid black; padding: 10px;">金額</th>
          </tr>
          <% @data.each_with_index do |row, index| %>
            <tr>
              <% row.each do |key,value| %>
                <td style="border: 1px solid black; padding: 10px; text-align: center;"><%= value %></td>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
        <div>
          <div class="right-side">
            <table>
              <tr>
                <th style="border: 1px solid black; padding: 10px;">日付</th>
                <th style="border: 1px solid black; padding: 10px;">出金合計</th>
                <th style="border: 1px solid black; padding: 10px;">入金合計</th>
              </tr>
              <% @total_outflow.each do |date, total| %>
                <tr>
                  <td style="border: 1px solid black; padding: 10px; text-align: center;"><%= date %></td>
                  <td style="border: 1px solid black; padding: 10px; text-align: center;"><%= @total_outflow[date] %></td>
                  <td style="border: 1px solid black; padding: 10px; text-align: center;"><%= @total_Inflow[date] %></td>
                </tr>
              <% end %>
            </table>
          </div>
          <div class="total-table">
            <h2>3月の出金合計</h2>
            <table>
              <tr>
                <th style="border: 1px solid black; padding: 10px;">合計金額</th>
              </tr>
              <tr>
                <td style="border: 1px solid black; padding: 10px; text-align: center;">
                  <%= @total_outflow.values.sum %>
                </td>
              </tr>
            </table>
          </div>
        </div>
    </div>

  <% else %>
    ログインしてください。
  <% end %>
</main>

app/views/users/show.html.erb
<main class="main-body">
  <div class="user-wrapper">
      <h1 class="account">アカウント</h1>
    <div class="user-main-wrapper">
      <h2 class="bar-title">基本情報</h2>
        <div class="user-about">
          <div class="user-info">
            <div class="user-name">
              ユーザー名：
              <%= current_user.nickname %>
            </div>
            <div class="user-email">
              メールアドレス：
              <%= current_user.email %>
            </div>
          </div>
            <%= link_to "編集する", "#", class:"edit_btn" %>
        </div>
    </div>
  </div>
</main>